name: 8x Daily API Trigger
on:
  schedule:
    - cron: '0 */3 * * *'
  workflow_dispatch:

jobs:
  execute-api-call:
    runs-on: ubuntu-latest
    permissions:
      actions: write  # This is critical for the GitHub API to work
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - run: pip install requests
      - name: Run Script
        env:
          URL_A: ${{ secrets.URL_A }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python script.py
